### PR TITLE
Soft docs / tutorial using tintin

### PR DESCRIPTION
**Pull request by mcwitt**
Preview [here](https://htmlpreview.github.io/?https://github.com/hasktorch/hasktorch/blob/90518c5f96519448eba1ab287ba7d08f78226b5a/hasktorch/public/tutorial/index.html) (I'll keep this up-to-date for the PR and remove before merging).

To build & view the tintin docs (tested on NixOS):
```shell
mv stack-8.10.2.yaml stack.yaml
cd hasktorch
stack exec tintin -- run # should work(?) but broken for me (see below)
open .stack-work/tintin/rendered/index.html
```
Since `stack exec tintin -- run` didn't work for me, I instead did
```shell
stack install tintin
~/.local/bin/tintin run
```

### Things done / to do
- [x] add initial skeleton
- [x] update package synopsis in cabal file (tintin uses this as subtitle)
- [x] add sections
- [x] copy/edit content from #516
- [ ] initial editing
- [ ] feedback/edit cycles
- [x] hook to auto-generate site?
- [ ] others I haven't thought of

### CODE REVIEW

**Comment by junjihashimoto** [comment]
I appreciate your help.
I think it is useful  in the current state.
If you want to deploy the document automatically, try adding [this code](https://github.com/hasktorch/hasktorch/blob/master/.github/workflows/nix-haddock-linux.yml#L32-L41)  to github-actions.

**Comment by mcwitt** [comment]
@junjihashimoto thanks for the reference. I'll try to get it set up with github actions. I think the tutorial could still use quite a bit of work, but maybe best to get something out there and then iterate.

**Comment by austinvhuang** [comment]
Exactly right @mcwitt! We will keep iterating on it, but this is still far better than no tutorial at all, which is the current state of affairs.

**Comment by junjihashimoto** [comment]
LGTM!
Thanks for getting this done.

**Pull request merged**
