### PR TITLE
Format examples

### PR DESCRIPTION
**Pull request by mcwitt**
- Replaces usage of [deprecated](https://stackoverflow.com/questions/7438600/datatypecontexts-deprecated-in-latest-ghc-why) `DatatypeContexts` with GADTs to allow formatting (Ormolu can't handle this)
- Formats all examples using Ormolu

Still to do in part 2:
- Either remove mention of `cabal test examples` in readme or add back the test suite (removed in 42f7f68d9236fe407ce2fe0ef65aeef1a04874df)
- Fix linting errors in examples where it makes sense
- Split up monolithic cabal file

### CODE REVIEW

**Comment by tscholak** [comment]
🙌  for splitting up the cabal file

**Comment by tscholak** [comment]
(the rest is also awesome)

**Comment by mcwitt** [comment]
I figured this would be a good opportunity to learn something about [Turtle](https://hackage.haskell.org/package/turtle) (which I'm loving so far!) and started a [script](https://github.com/mcwitt/turtle-scripts/blob/master/hasktorch-modularize-examples/src/Lib.hs) to do the cabal split systematically. I'll likely be pretty busy for the next 2 weeks with work and travel, so if anyone wants to pick this up feel free! (also happy to rebase this on any changes to the examples).

**Comment by austinvhuang** [comment]
@mcwitt is this okay (or close) to merge as is? Would like to get some of your improvements in before too many upstream changes require updating this. Thanks!

**Comment by mcwitt** [comment]
@austinvhuang sorry about letting this get so stale - I'm just getting back from an extended trip. I think it makes sense to merge close to as-is. I'll just do a little bit of cleanup this morning and plan to merge it later today

**Comment by mcwitt** [comment]
> :raised_hands: for splitting up the cabal file

Still plan to do this in a separate PR :slightly_smiling_face:

**Pull request merged**
