### PR TITLE
Add logical and/or

### PR DESCRIPTION
**Pull request by tycho01**
now gives a few errors like:
```
src/Torch/Internal/Unmanaged/Native.hs:2116:29: error:
     error: ‘logical_and’ is not a member of ‘at’
```

### CODE REVIEW

**Comment by tycho01** [comment]
do we have an open issue investigating an upgrade to 1.5?

**Comment by junjihashimoto** [comment]
For now, I do not have the issue except for upgrading c++11 to c++14.

**Comment by junjihashimoto** [comment]
logical_and  is avaiable on master-branch.
https://hasktorch.github.io/hasktorch-0.2.0.0/html/src/Torch.Functional.Internal.html#logical_and

**Comment by tycho01** [comment]
thanks! closing.

**Pull request closed without merging**
