### PR TITLE
Fix CI of macos and change the target of cachix from cuda9 to cuda11

### PR DESCRIPTION
**Pull request by junjihashimoto**

### CODE REVIEW

**Comment by junjihashimoto** [comment]
image

**Comment by tscholak** [comment]
@junjihashimoto do you want to merge my PR #488 in here? you need to update the cachix actions, what I've already done.

**Comment by junjihashimoto** [comment]
@tscholak Yes. I'm going to merge from now on.

**Comment by junjihashimoto** [comment]
@tscholak  All checks have passed. Thx!

**Pull request merged**
