### PR TITLE
Update dependencies, remove HLS from custom-tools

### PR DESCRIPTION
**Pull request by mcwitt**
Since haskell-language-server 1.0 is now in Hackage, we no longer need to add it as a custom tool.

Also removed `nixpkgs-2009` from `sources.json`, because it seemed like this was unused (?)

### CODE REVIEW

**Comment by tscholak** [comment]
thank you! this will now take forever to build ;)

**Comment by mcwitt** [comment]
> thank you! this will now take forever to build ;)

At what stage does cachix get updated with the new artifacts?

**Comment by tscholak** [comment]
> At what stage does cachix get updated with the new artifacts?
Only at the very end :/

**Comment by tscholak** [comment]
@mcwitt when I get the chance, I will try to build the `nix-macos` derivation locally and push it to cachix. not sure what's going on with `nix-jupyterlab`

**Comment by mcwitt** [comment]
> not sure what's going on with nix-jupyterlab
@tscholak looks to me like it ran out of memory (error 137 at the end). Is there a way we can bump that up?

**Comment by tscholak** [comment]
quick update: I have to use a newer nixpkgs (nixpkgs-unstable probably) because otherwise I think Big Sur won't be supported.

**Comment by tscholak** [comment]
or, alternatively, I build gcc on another machine with an older version of macOS, and push to cachix from there.

**Comment by tscholak** [comment]
@mcwitt can you merge https://github.com/hasktorch/hasktorch/tree/mcwitt-update-deps into your branch please?

**Comment by tscholak** [comment]
@mcwitt I've got hls 1.0 working again on Mac OS Big Sur with ghc 8.10.4. Please merge https://github.com/hasktorch/hasktorch/tree/mcwitt-update-deps into this branch at your earliest convenience so that we can wrap this up.

**Comment by mcwitt** [comment]
@tscholak done!

**Pull request merged**
