### PR TITLE
To build gradually typed api, install the binary of libtokenizers

### PR DESCRIPTION
**Pull request by junjihashimoto**
This is to use gradually typed api in workflows other than nix.
I update get-deps.sh to install the shared library of libtokenizers_haskell.

### CODE REVIEW

**Comment by tscholak** [comment]
Oh cool, thanks for that!

**Comment by junjihashimoto** [comment]
Is it a version mismatch?
image
https://github.com/hasktorch/hasktorch/pull/604/checks?check_run_id=3257965718

**Comment by tscholak** [comment]
yes, I don't know which package, though

**Comment by tscholak** [comment]
Oops, sorry about the doctests. I can't run them locally on my Mac without docker because in the nix shell the doctest executable crashes with an unknown symbol error

**Comment by junjihashimoto** [comment]
It's fine. I think the current test will pass.

**Comment by junjihashimoto** [comment]
BTW, some builds are over an hour.
I want to cache .stack-work and dist-newstyle.
It may differ from the result of clean build.

**Comment by junjihashimoto** [comment]
@tscholak 
doctests also seems to crash without nix on macos.
https://github.com/hasktorch/hasktorch/runs/3261213096

**Comment by tscholak** [comment]
This looks fixable though:

Linking /Users/runner/work/hasktorch/hasktorch/dist-newstyle/build/x86_64-osx/ghc-8.10.5/hasktorch-gradually-typed-0.2.0.0/build/doctests/doctests ...
56
ld: warning: directory not found for option '-L/Users/runner/work/hasktorch/hasktorch/deps/mklml/lib'
57
ld: warning: directory not found for option '-L/Users/runner/work/hasktorch/hasktorch/deps/libtorch/lib'
58
ld: warning: directory not found for option '-L/Users/runner/work/hasktorch/hasktorch/deps/tokenizers/lib'
59
ld: warning: directory not found for option '-L/Users/runner/work/hasktorch/hasktorch/deps/mklml/lib'
60
ld: warning: directory not found for option '-L/Users/runner/work/hasktorch/hasktorch/deps/libtorch/lib'
61
ld: warning: directory not found for option '-L/Users/runner/work/hasktorch/hasktorch/deps/tokenizers/lib'
62
Preprocessing library for hasktorch-gradually-typed-0.2.0.0..
63
Building library for hasktorch-gradually-typed-0.2.0.0..
64
ld: warning: directory not found for option '-L/Users/runner/work/hasktorch/hasktorch/deps/mklml/lib'
65
ld: warning: directory not found for option '-L/Users/runner/work/hasktorch/hasktorch/deps/libtorch/lib'
66
ld: warning: directory not found for option '-L/Users/runner/work/hasktorch/hasktorch/deps/tokenizers/lib'
67
ld: warning: directory not found for option '-L/Users/runner/work/hasktorch/hasktorch/deps/mklml/lib'
68
ld: warning: directory not found for option '-L/Users/runner/work/hasktorch/hasktorch/deps/libtorch/lib'
69
ld: warning: directory not found for option '-L/Users/runner/work/hasktorch/hasktorch/deps/tokenizers/lib'

**Comment by junjihashimoto** [comment]
@tscholak 
The warnings come out to install libtorch with apt.
The settings is required when using get-deps.
It's annoying, but it seems good to ignore it to handle both.

**Comment by tscholak** [comment]
In other words, the things I posted are not the reason for why the doctests fail on macOS+cabal?

Do you have access to the logs?

**Comment by junjihashimoto** [comment]
@tscholak 
I've looked at the log, but it seems that there is no problem other than the warning of the path.

I think the error is related to this issue.
https://github.com/sol/doctest/issues/72

hasktorch package has the same issue.
So I wrote the comment in cabal. (I forgot.)
https://github.com/hasktorch/hasktorch/blob/master/hasktorch/hasktorch.cabal#L21

**Comment by tscholak** [comment]
Right, the issue I linked to mentions the "duplicate symbol" problem. Ok, so this is not nix specific then. Good to know

**Comment by junjihashimoto** [comment]
@tscholak 
If I look closely, https://github.com/sol/doctest/issues/72 and https://github.com/hasktorch/hasktorch/pull/282#issuecomment-605413945 look different.

If it just can't link, we may be able to improve it by adding the -dynamic option.
https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/flags.html

**Comment by junjihashimoto** [comment]
-dynamic flag can not be used with ghci.
https://github.com/hasktorch/hasktorch/runs/3261999938

**Pull request merged**
