### PR TITLE
Documentation for TensorFactories.hs and Examples README FIXED

### PR DESCRIPTION
**Pull request by Chetank99**
Parameter description and Documentation for the file

In examples README, the regression and xor-mlp links are broken. Fixed it.

### CODE REVIEW

**Comment by Chetank99** [comment]
CI failing for example README. Could not understand why. The links were broken and it was just a simple fix to correctly redirect :confused:

**Comment by tscholak** [comment]
@Chetank99 you had bad luck. there's one unit test that needs to be fixed. we are aware of this problem, see https://hasktorch.slack.com/archives/GP0GSE2UX/p1581427118074500. it fails randomly because sometimes the random initialization produces an invalid test tensor. I restarted the tests, it's unlikely it happens again.

**Comment by Chetank99** [comment]
@tscholak It's still failing. Is there some problem with specifically the README? Because the TensorFactories.hs file is okay

**Comment by tscholak** [comment]
the current issue is different. something is wrong with git:
```
From https://github.com/hasktorch/hasktorch
 * [new branch]      austin               -> origin/austin
 * [new branch]      ayush1999            -> origin/ayush1999
 * [new branch]      circle-8-6_8-4       -> origin/circle-8-6_8-4
 * [new branch]      dev                  -> origin/dev
 * [new branch]      feature/jupyter      -> origin/feature/jupyter
 * [new branch]      gh-pages             -> origin/gh-pages
 * [new branch]      initializers         -> origin/initializers
 * [new branch]      master               -> origin/master
 * [new branch]      migrate-initializers -> origin/migrate-initializers
 * [new branch]      optimizers           -> origin/optimizers
 * [new branch]      release-cleanup      -> origin/release-cleanup
 * [new branch]      untyped-mnist        -> origin/untyped-mnist
 * [new tag]         v0.0.1               -> v0.0.1
 * [new tag]         v0.0.1.1             -> v0.0.1.1
git checkout --progress --force 0b61db43593cc138428f28b09622d5b5ab2a3656
##[error]fatal: reference is not a tree: 0b61db43593cc138428f28b09622d5b5ab2a3656
Removed matchers: 'checkout-git'
##[error]Git checkout failed with exit code: 128
##[error]Exit code 1 returned from process: file name '/Users/runner/runners/2.165.2/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Repository.v1_0.CheckoutTask, Runner.Plugins"'.
```
Can you make a no-op change and push to the branch again please?

**Comment by junjihashimoto** [comment]
This problem may be the same as [this issue](https://github.com/actions/checkout/issues/23
).

**Comment by Chetank99** [comment]
@junjihashimoto YES it worked!
https://github.com/hasktorch/hasktorch/pull/295
Thank You

**Pull request closed without merging**
