### PR TITLE
fix/nix macos and unzip, too

### PR DESCRIPTION
**Pull request by tscholak**
opening this PR to run the code against CI....

### CODE REVIEW

**Comment by junjihashimoto** [comment]
The unzip works well.
Thx!

**Comment by tscholak** [comment]
@junjihashimoto I saw that you closed your PR. is something wrong?

**Comment by junjihashimoto** [comment]
We need this modification. The pr is a duplicate.
So I closed it.

**Comment by tscholak** [comment]
Oh, you could have just taken it since it’s so trivial.

**Comment by junjihashimoto** [comment]
Thx!

**Pull request merged**
