### PR TITLE
Fix empty tensors

### PR DESCRIPTION
**Pull request by junjihashimoto**
See https://github.com/hasktorch/hasktorch/issues/520 .

### CODE REVIEW

**Review by tscholak — COMMENTED** [review]
nice, this was quick!

**Comment by junjihashimoto** [comment]
I'm not sure how to use an empty tensor different from zero tensor.
But it seems to behave like pytorch.

**Comment by junjihashimoto** [comment]
pytorch : 
image

hasktorch:
image

**Comment by tscholak** [comment]
Interesting, I need to check if I have implemented broadcasting correctly

**Comment by junjihashimoto** [comment]
Typed tensor works correctly too.
image

**Pull request merged**
