### PR TITLE
Add serialize-function for tensor

### PR DESCRIPTION
**Pull request by junjihashimoto**
This pr supports serialize-function using checkpoint-file of pytorch.

### CODE REVIEW

**Comment by tscholak** [comment]
OMG that's awesome, I had no idea it could be done with libtorch!

**Comment by junjihashimoto** [comment]
I read today and realized that I can do it.

**Comment by tscholak** [comment]
question: do you know if this tensorlist you're dumping/loading has to be on cpu?

**Comment by junjihashimoto** [comment]
That's a good question.
I have to test it.
Before the test, I checked some samples using save and load.
Probably, save supports both cpu and gpu, on the other hand load outputs the data to cpu only.

**Comment by junjihashimoto** [comment]
Yes, I will. 
Because torch's serialize supports deserialization with the correct type.

**Pull request merged**
